version: "3.3"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: diplom-nginx
        ports:
            - "8088:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/diplom
            - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fpm
            - pgsql
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        container_name: diplom-php
        volumes:
            - ./:/var/www/diplom
        links:
            - pgsql
    pgsql:
        image: postgres:13.3
        container_name: diplom-pg
        environment:
                POSTGRES_DB: "diplom"
                POSTGRES_USER: "develop"
                POSTGRES_PASSWORD: "develop"
                PGDATA: "var/lib/diplom/pgdata"
        ports:
            - "5432:5432"
        volumes:
            -   .:/var/lib/diplom

