version: "3.4"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: pet-nginx
        ports:
            - "8000:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/pet
            - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fpm
            - pgsql
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        container_name: pet-php
        volumes:
            - ./:/var/www/pet
        links:
            - pgsql
    pgsql:
        image: postgres:13.3
        container_name: pet-pg
        environment:
                POSTGRES_DB: " pet"
                POSTGRES_USER: "develop"
                POSTGRES_PASSWORD: "develop"
                PGDATA: "var/lib/pet/pgdata"
        ports:
            - "5432:5432"
        volumes:
            -   .:/var/lib/pet

